apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops8
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops8
  template:
    metadata:
      labels:
        app: mlops8
    spec:
      containers:
      - name: mlops8
        image: us-central1-docker.pkg.dev/lofty-voyage-461011-f1/mlops8/mlops8_image:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: mlops8
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer